app_main_site/urls.py
from django.urls import path

from . import views

app_name = 'app_main_site'

urlpatterns = [
    path("", views.home, name="home"),
    path("profile/", views.profile, name="profile"),
    path("profile/update", views.update_profile, name="update_profile"),

    path('registration/', views.custom_registration, name='registration'),
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
]

project_safety_minder/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # path('safety-minder/', include('django.contrib.auth.urls')),  
    path('admin/', admin.site.urls),
    path("safety-minder/", include("app_main_site.urls"))
]

app_main_site/models.py
from django.db import models

# Create your models here.

app_users/models.py
from django.db import models

from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_('The Email field must be set'))
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)
    

class CustomUser(AbstractUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)

    username = models.CharField(max_length=30, unique=False, blank=True, null=True)
    
    full_name = models.CharField(max_length=100, unique=True, blank=False, null=False)
    badge = models.PositiveIntegerField(unique=True, null=True)
    position = models.CharField(max_length=50, unique=False, blank=False, null=False)
    area = models.CharField(max_length=50, unique=False, blank=False, null=True)
    line_manager = models.CharField(max_length=100, unique=False, blank=False, null=True)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    class Meta:
        verbose_name = "Custom User"
        verbose_name_plural = "Custom Users"

app_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm


from .models import CustomUser

class ProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'full_name', 'badge', 'position', 'area', 'line_manager')

        
class RegisterUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'full_name', 'badge', 'position', 'area', 'line_manager')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label='Email',
        widget=forms.TextInput(attrs={"class": "form-input"})
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={"class": "form-input"})
    )


class ChangePasswordForm(PasswordChangeForm):
    class Meta:
        model = CustomUser

app_main_site/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseBadRequest
from django.urls import reverse
from django.forms.models import model_to_dict

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required, permission_required

from app_users.forms import RegisterUserForm, LoginUserForm, ProfileForm
from app_users.models import CustomUser


def custom_registration(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("app_main_site:home")
    else:
        form = RegisterUserForm()

    return render(request, "registration/registration.html", {"form": form})

def custom_login(request):
    if request.method == "POST":
        form = LoginUserForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect("app_main_site:profile")
    else:
        form = LoginUserForm()
    return render(request, "registration/login.html", {"form": form})

def custom_logout(request):
    logout(request)
    return redirect('app_main_site:home')

def home(request):
    context = {
        "home": "home page"
    }
    return render(request, "app_main_site/home.html", context)

def profile(request):
    profile = ProfileForm(data=model_to_dict(CustomUser.objects.get(pk=request.user.id)))
    context = {
        "profile": profile
    }
    return render(request, "app_main_site/profile.html", context)

    
def update_profile(request):
    current_profile = get_object_or_404(CustomUser, pk=request.user.id)   
    if request.method == "POST":    
        form = ProfileForm(request.POST, instance=current_profile)
        if form.is_valid():
            form.save()
            return redirect(reverse("app_main_site:profile"))
    else:
        form = ProfileForm(instance=current_profile)
        return render(request, "app_main_site/update_profile.html", {"form": form})

app_main_site/templates/app_main_site/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
    <body>
        
        <header class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-md">
                <!-- Логотип или название (Safety) по центру -->
                <a class="navbar-brand mx-auto" href="{% url 'app_main_site:home' %}">Safety Minder</a>
        
                <!-- Кнопка Login справа -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'app_main_site:profile' %}" class="btn btn-info">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'app_main_site:logout' %}" class="btn btn-danger">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{% url 'app_main_site:registration' %}" class="btn btn-outline-primary">Registration</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'app_main_site:login' %}" class="btn btn-primary">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </header>

        <main class="container py-4">
            {% block content %}{% endblock %}
        </main>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </body>
</html>

app_main_site/templates/app_main_site/home.html
{% extends "app_main_site/base.html" %}

{% block title %}Home{% endblock %}


{% block content %}
    {{ home }}
{% endblock%}

app_main_site/templates/app_main_site/profile.html
{% extends "app_main_site/base.html" %}

{% block title %}Profile{% endblock %}


{% block content %}

    {% for item in profile %}
        <div class="row">
            <div class="col-md-4 col-12">
                <h5>{{ item.label }}</h5>
            </div>
            <div class="col-md-8 col-12">
                <p>{{ item.data }}</p>
            </div>
        </div>
    {% endfor %}
    <!-- <div class="row">
        <div class="col-md-4 col-12">
            <h5>Full name</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{profile.full_name }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Badge</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{profile.badge}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Position</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{profile.position}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Area</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{profile.area}}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Line manager</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{profile.line_manager}}</p>
        </div>
    </div> -->

    <a href="{% url 'app_main_site:update_profile' %}">
        <button type="button" class="btn btn-outline-info">Update</button>
    </a>
{% endblock%}

app_main_site/templates/app_main_site/update_profile.html
{% extends "app_main_site/base.html" %}

{% block title %}Update -pofile{% endblock %}


{% block content %}
<form method="post" class="update_profile">
    {% csrf_token %}
    {% for item in form %}
        <div class="row">
            <div class="col-md-4 col-12">
                <h5>{{ item.label_tag }}</h5>
            </div>
            <div class="col-md-8 col-12">
                <p>{{ item }}</p>
            </div>
        </div>
    {% endfor %}
    <button type="submit">Update profile</button>
</form>
{% endblock%}